version: '3.8'

services:
  # MongoDB 데이터베이스
  mongodb:
    image: mongo:7.0
    container_name: cardlet-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cardlet_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cardlet-network

  # 백엔드 서비스
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cardlet-backend
    restart: unless-stopped
    environment:
      - SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/cardlet_db?authSource=admin
      - DATABASE_NAME=cardlet_db
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - cardlet-network

  # 프론트엔드 서비스
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cardlet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cardlet-network

volumes:
  mongodb_data:

networks:
  cardlet-network:
    driver: bridge 