version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cardlet-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cardlet_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cardlet-network

  backend:
    image: kang0719/ocr-backend:v7  # ← 변경됨!
    container_name: cardlet-backend
    restart: unless-stopped
    environment:
      - SECRET_KEY=E261SKHCeBfNDVD7Ij03ID3gdmLVjm0v2CVf3hIdHELn0fLiqLqFiBtqB8CN6l2NiHLcowZN4mt
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/cardlet_db?authSource=admin
      - DATABASE_NAME=cardlet_db
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - cardlet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://210.109.82.112:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: kang0719/ocr-frontend:v13  # ← 새로 빌드된 이미지
    container_name: cardlet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cardlet-network

volumes:
  mongodb_data:

networks:
  cardlet-network:
    driver: bridge
