apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cardlet-ocr
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/cardlet-backend:latest  # 실제 이미지 경로로 변경
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cardlet-secrets
              key: SECRET_KEY
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: cardlet-config
              key: MONGODB_URL
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: cardlet-config
              key: DATABASE_NAME
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: cardlet-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: cardlet-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: cardlet-config
              key: DEBUG
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cardlet-ocr
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP 