apiVersion: v1
kind: ConfigMap
metadata:
  name: cardlet-config
  namespace: cardlet-ocr
data:
  # 백엔드 설정
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  DATABASE_NAME: "cardlet_db"
  DEBUG: "false"
  
  # MongoDB 설정 (실제 운영에서는 외부 MongoDB 사용 권장)
  MONGODB_URL: "mongodb://mongodb-service:27017" 