apiVersion: v1
kind: Secret
metadata:
  name: cardlet-secrets
  namespace: cardlet-ocr
type: Opaque
data:
  # JWT 시크릿 키 (base64 인코딩 필요)
  # 실제 배포 시에는 강력한 시크릿 키로 변경하세요
  # echo -n "your-super-secret-jwt-key-change-this-in-production" | base64
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  
  # MongoDB 인증 정보 (필요한 경우)
  # MONGODB_USERNAME: <base64-encoded-username>
  # MONGODB_PASSWORD: <base64-encoded-password> 